# .github/workflows/deploy-lemp.yml
name: Deploy to LEMP Stack

on:
  push:
    branches: [ main ]

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  APP_DIR: /var/www/nextgenbeing

jobs:
  test:
    runs-on: ubuntu-latest
    # ... same test configuration as before

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Add known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ env.APP_DIR }}

          # Pull latest changes
          sudo -u www-data git fetch origin
          sudo -u www-data git reset --hard origin/main

          # Install dependencies
          sudo -u www-data composer install --no-dev --optimize-autoloader
          sudo -u www-data npm install --silent
          sudo -u www-data npm run build

          # Run migrations
          sudo -u www-data php artisan migrate --force

          # Optimize application
          sudo -u www-data php artisan config:cache
          sudo -u www-data php artisan route:cache
          sudo -u www-data php artisan view:cache

          # Set permissions
          sudo chown -R www-data:www-data ${{ env.APP_DIR }}
          sudo chmod -R 755 ${{ env.APP_DIR }}
          sudo chmod -R 775 ${{ env.APP_DIR }}/storage
          sudo chmod -R 775 ${{ env.APP_DIR }}/bootstrap/cache

          # Restart services
          sudo systemctl restart nginx
          sudo systemctl restart php8.4-fpm

          echo "✅ Deployment completed successfully!"
